### ISSUE TITLE
Validation fails on nested slicing

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [hapifhir/org.hl7.fhir.core#24]
If I create a profile on Observation where I slice .component on value/code.coding.code, add a slice 'component1' and then again slice the component1.coding on value/code, the validator fails with the following error message:
```
 Error @ Observation.component (line xx, col yy) : Error in discriminator at Observation.component:component1.code.coding: slicing found
```

See the attached example profile + instance. The issue occurs both with FHIR version 3.0.1 and 4.0.0

[Test profile + instance](https://github.com/hapifhir/org.hl7.fhir.core/files/3186108/NestedSlicingTest.zip)

**Comment by pieter-edelman-nictiz** [comment]
See also this discussion on the FHIR chat: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Java.20validator.20and.20Simplifier.20disagree.20on.20slice.20validity

**Comment by grahamegrieve** [comment]
fixed

**Comment by pieter-edelman-nictiz** [comment]
Using the latest snapshot of the validator (`Built 2019-06-11T07:46:57.733+10:00 - Git 9a344b251c77`), I still get an error on the provided example, albeit a different one:
```
*FAILURE* validating NestedSlicingTestInstance.xml:  error:1 warn:0 info:0
  Error @ Observation.component (line 13, col16) : Error in discriminator at Observation.component:component1.code.coding: found a sliced element while resolving the fixed value for one of the slices
```
