### ISSUE TITLE
Bug: erroneous error `This element has a Binding but the types to do not make this kind of constraint relevant` 

### ISSUE THREAD

**Issue by david-simons** [hapifhir/org.hl7.fhir.core#908]
This commit last week introduced the following issues for us (fhirVersion 3.0.2, latest HL7 Validator 5.6.56)
<https://github.com/hapifhir/org.hl7.fhir.core/commit/2f6dfa62cabf9252be4275b9c22c4f461060dbff>
@grahamegrieve 

I suspect a number of Resource types are missing, incl. 

- `Observation`, 
- `Contract`, 
- `Endpoint`, 
- `Device`, 
- `Extension`,
- `Extension` 
- ` ImagingStudy`  
- `DiagnosticReport`
- `Composition`
- `Organization`
(at least these give us errors)

that need a `has-binding`, `max-length`, etc. characteristic, which they do not get erroneously as a plain `Resource` .

```
FHIR Validation tool Version 5.6.56 (Git# 51199251e858). Built 2022-08-26T21:14:55.137Z (4 days old)
    Java:   1.8.0_345 from /__w/_tool/jdk/8.0.345/x64/jre on amd64 (64bit). 1712MB available
    Paths:  Current = /__w/FHIR/FHIR, Package Cache = /root/.fhir/packages
    Params: -version 3.0.2 -ig profiles-folder
```

![image](https://user-images.githubusercontent.com/6153327/187705703-44f68d22-8633-492f-a084-42268c169078.png)

**Comment by grahamegrieve** [comment]
what types do those elements have?

**Comment by david-simons** [comment]
Element[4] in the above snippet, is a Device.identifier.type having a binding.

```
    <element id="Device.identifier:instrumentNumber.type">
      <path value="Device.identifier.type" />
      <patternCodeableConcept>
        <coding>
          <system value="https://www.fhir.philips.com/3.0/CodeSystem/common/dataType/identifier-v1/ExtendedIdentifierTypeCodeSystem" />
          <code value="INO" />
        </coding>
      </patternCodeableConcept>
      <binding>
        <strength value="extensible" />
        <valueSetReference>
          <reference value="https://www.fhir.philips.com/3.0/ValueSet/common/core/deviceManagement-v1/operations/DeviceIdentifierTypesValueSet" />
        </valueSetReference>
      </binding>
    </element>
```

**Comment by david-simons** [comment]
Tested using a HL7Validator version `older = 5.6.33` instead of `latest = 5.6.56` - this is not giving these issues....

**Comment by grahamegrieve** [comment]
Fixed next time I commit and release

**Comment by david-simons** [comment]
Between 5.6.33 and 5.6.57 (including PR #908) - the following error+warning still showing for us - the error still related to this issue #908.

![image](https://user-images.githubusercontent.com/6153327/188113824-e3463e01-e896-43d1-9d02-5c05dd4a2428.png)

```
 <element id="ImagingStudy.series.extension:dsSeriesAvailabilityStatus">
      <path value="ImagingStudy.series.extension" />
      <sliceName value="dsSeriesAvailabilityStatus" />
      <definition value="Can be Available, Processing or Unavailable." />
      <max value="1" />
      <type>
        <code value="Extension" />
        <profile value="https://.../DsSeriesAvailabilityStatusExtension" />
      </type>
      <binding>
        <strength value="required" />
        <description value="DICOMStore ImagingStudy.dsSeriesAvailabilityStatus" />
        <valueSetUri value="https://.../DsSeriesAvailabilityStatusValueSet" />
      </binding>
    </element>
  </differential>
```

**Comment by grahamegrieve** [comment]
Oh. missed that. it is legal, though mainly for legacy reasons.
